# Generated by Django 3.2.2 on 2021-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfols', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='imageurl',
            field=models.CharField(default='notjustok', max_length=80),
        ),
    ]
